version: 0.1
phases:
    install:
        commands:
            - 'npm install'
    build:
        commands:
            - 'npm run compile'
artifacts:
    type: zip
    files:
        - package.json
        - package-lock.json
        - 'build/**/*'
        - README.md
