export const CHARACTER_ID_MAPPINGS: Map<number, string> = new Map<number, string>([
    [0, "Captain Falcon"],
    [1, "Donkey Kong"],
    [2, "Fox"],
    [3, "Mr. Game & Watch"],
    [4, "Kirby"],
    [5, "Bowser"],
    [6, "Link"],
    [7, "Luigi"],
    [8, "Mario"],
    [9, "Marth"],
    [10, "Mewtwo"],
    [11, "Ness"],
    [12, "Peach"],
    [13, "Pikachu"],
    [14, "Ice Climbers"],
    [15, "Jigglypuff"],
    [16, "Samus"],
    [17, "Yoshi"],
    [18, "Zelda"],
    [19, "Sheik"],
    [20, "Falco"],
    [21, "Young Link"],
    [22, "Dr. Mario"],
    [23, "Roy"],
    [24, "Pichu"],
    [25, "Ganondorf"],
    [26, "Master Hand"],
    [27, "Wireframe Male"],
    [28, "Wireframe Female"],
    [29, "Giga Bowser"],
    [30, "Crazy Hand"],
    [31, "Sandbag"],
    [32, "Popo"],
    [33, "User Select(Event) / None"],
]);

export const CHARACTER_IMAGE_FILE_PATH = "public/characters/"
export const GAME_START_OFFSET = -123
